# Repo Explainer
spring:
  application:
    name: repo-explainer

  # --- AI Configuration ---
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: llama3.2 # 3B parametreli küçük model, 4GB VRAM'e sığması için
    mcp:
      server:
        protocol: STREAMABLE
        stdio: false
        type: SYNC

      # ---MCP Client---
      client:
        enabled: true
        name: repo-explainer-client
        type: SYNC
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            git-mcp:
              url: http://mcp-git-server:8081
              endpoint: /mcp
            sql-explainer:
              url: http://sqlmcp-server:8082
              endpoint: /mcp

server:
  port: ${SERVER_PORT:8084}

# --- GitHub Token ---
github:
  token: ${GITHUB_TOKEN:}

# --- Logging ---
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    com.repoexplainer: DEBUG
