spring:
  application:
    name: FileReader-mcp-server
  ai:
    mcp:
      server:
        annotation-scanner:
          enabled: true
        protocol: STREAMABLE
        stdio: false
        type: SYNC

server:
  port: ${SERVER_PORT:8083}
