spring.application.name=Git-mcp-server
spring.ai.mcp.server.annotation-scanner.enabled=true

server.port=${SERVER_PORT:8002}

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=SYNC